// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHwzPYQYNvxTUqSNgTZT6MWAk0K1Mj1hg',
    appId: '1:955584471319:web:5dc7d79182426ce71c1752',
    messagingSenderId: '955584471319',
    projectId: 'flutterapplication-707cd',
    authDomain: 'flutterapplication-707cd.firebaseapp.com',
    storageBucket: 'flutterapplication-707cd.firebasestorage.app',
    measurementId: 'G-VXYNWJMWYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYsmfR7sQxWclbqOVk2XPD6mBmaGHhj0Q',
    appId: '1:955584471319:android:bb8b8bb9185c1f541c1752',
    messagingSenderId: '955584471319',
    projectId: 'flutterapplication-707cd',
    storageBucket: 'flutterapplication-707cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpvAPWJPIEww0bPSxtQrQ_QQhbsZEM9T8',
    appId: '1:955584471319:ios:37190856e2c1bce11c1752',
    messagingSenderId: '955584471319',
    projectId: 'flutterapplication-707cd',
    storageBucket: 'flutterapplication-707cd.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpvAPWJPIEww0bPSxtQrQ_QQhbsZEM9T8',
    appId: '1:955584471319:ios:37190856e2c1bce11c1752',
    messagingSenderId: '955584471319',
    projectId: 'flutterapplication-707cd',
    storageBucket: 'flutterapplication-707cd.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHwzPYQYNvxTUqSNgTZT6MWAk0K1Mj1hg',
    appId: '1:955584471319:web:b6d17c7bce367a381c1752',
    messagingSenderId: '955584471319',
    projectId: 'flutterapplication-707cd',
    authDomain: 'flutterapplication-707cd.firebaseapp.com',
    storageBucket: 'flutterapplication-707cd.firebasestorage.app',
    measurementId: 'G-LVNGYGL683',
  );
}
